### ISSUE TITLE
The results of running in IDEA did not meet expectations.

### ISSUE THREAD

**Issue by NekoCaffeine** [jerkar/jeka#140]
at [JkPluginIntellij#allIml](https://github.com/jerkar/jeka/blob/e14c451540/dev.jeka.core/src/main/java/dev/jeka/core/tool/builtins/intellij/JkPluginIntellij.java#L83-L104)

When running in `IDEA`, dependencies in subprojects cannot be parsed correctly and the corresponding `iml file` is generated.
This works fine in `cmd`.

subprojects dependencies (Build.java):
```java
private JkDependencySet dependencies() {
    return JkDependencySet.of()
            .withDefaultScopes(JkJavaDepScopes.COMPILE, JkJavaDepScopes.RUNTIME)
            .andFiles(getBaseTree().andMatching(true, "libs/*.jar").getFiles());
}
```

running in IDEA:
iml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compileRunner-output="false">
    <output url="file://$MODULE_DIR$/.idea/output/production"/>
    <output-test url="file://$MODULE_DIR$/.idea/output/test"/>
    <exclude-output/>
    <orderEntry type="inheritedJdk"/>
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/jeka/def" isTestSource="true"/>
          <excludeFolder url="file://$MODULE_DIR$/jeka/output"/>
      <excludeFolder url="file://$MODULE_DIR$/.idea/output"/>
    </content>
    <orderEntry type="sourceFolder" forTests="false"/>
    <orderEntry type="module-library" scope="TEST" exported="">
      <library>
        <CLASSES>
          <root url="jar://$JEKA_USER_HOME$/cache/wrapper/0.8.9.RELEASE/dev.jeka.jeka-core.jar!/"/>
        </CLASSES>
        <JAVADOC>
          <root url="jar://$JEKA_USER_HOME$/cache/wrapper/0.8.9.RELEASE/libs-javadoc/dev.jeka.jeka-core-javadoc.jar!/"/>
        </JAVADOC>
        <SOURCES>
          <root url="jar://$JEKA_USER_HOME$/cache/wrapper/0.8.9.RELEASE/libs-sources/dev.jeka.jeka-core-sources.jar!/"/>
        </SOURCES>
      </library>
    </orderEntry>
  </component>
</module>
```
log:
```
"C:\Program Files\AdoptOpenJDK\jdk-13.0.0.33-hotspot\bin\java.exe" --enable-preview -javaagent:C:\Users\HP\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\192.6603.28\lib\idea_rt.jar=64599:C:\Users\HP\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\192.6603.28\bin -Dfile.encoding=UTF-8 -classpath D:\Amadeus\Chocological\.idea\output\test;D:\Jeka\User\cache\wrapper\0.8.9.RELEASE\dev.jeka.jeka-core.jar Build
Picked up JAVA_TOOL_OPTIONS: -Dsun.jnu.encoding=utf-8  -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=1080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=1080
Resolving dependencies  ... 
│ 0 module leading to 0 artifact.
└ Done in 4 milliseconds.
Project Location : D:\Amadeus\Chocological
Published Module & version : amadeus:chocological:internal-SNAPSHOT
Sources : [D:\Amadeus\Chocological\src\main\java:all]
Resources : [D:\Amadeus\Chocological\src\main\resources:all, D:\Amadeus\Chocological\src\main\java:all & out:[**/*.java, *.java, **/package.html, package.html, **/doc-files, doc-files]]
Tests : [D:\Amadeus\Chocological\src\test\java:all]
Tests resources : [D:\Amadeus\Chocological\src\test\resources:all, D:\Amadeus\Chocological\src\test\java:all & out:[**/*.java, *.java, **/package.html, package.html, **/doc-files, doc-files]]
Java Source Version : 13
Source Encoding : UTF-8
Source file count : 0
Download Repositories : [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2]
Publish repositories : [file:/D:/Jeka/User/maven-publish-dir]
Declared Dependencies : 1 elements.
Defined Artifacts : [[main-artifact].jar, -sources.jar, -original.jar]

Execute 'java#showDependencies' to display details on dependencies.
Generating iml file on D:\Amadeus\Chocological\chocological-javac ... 
│ Generating Iml failed : Try to generate it using -CC=JkCommands option.
│ Resolving dependencies  ... 
│ │ 0 module leading to 0 artifact.
│ └ Done in 0 milliseconds.
│ Resolving dependencies  ... 
│ │ 0 module leading to 1 artifact.
│ └ Done in 0 milliseconds.
│ Iml file generated at D:\Amadeus\Chocological\chocological-javac\chocological-javac.iml
└ Done in 1601 milliseconds.
Generating iml file on D:\Amadeus\Chocological ... 
│ Resolving dependencies  ... 
│ │ 0 module leading to 0 artifact.
│ └ Done in 0 milliseconds.
│ Resolving dependencies  ... 
│ │ 0 module leading to 1 artifact.
│ └ Done in 0 milliseconds.
│ Iml file generated at D:\Amadeus\Chocological\Chocological.iml
└ Done in 547 milliseconds.
Iml file detected : chocological-javac\chocological-javac.iml
Iml file detected : Chocological.iml
File generated at : D:\Amadeus\Chocological\.idea\modules.xml

Process finished with exit code 0
```

running in cmd:
iml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compileRunner-output="false">
    <output url="file://$MODULE_DIR$/.idea/output/production"/>
    <output-test url="file://$MODULE_DIR$/.idea/output/test"/>
    <exclude-output/>
    <orderEntry type="inheritedJdk"/>
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/jeka/def" isTestSource="true"/>
      <sourceFolder url="file://$MODULE_DIR$/src/test/java" isTestSource="true"/>
      <sourceFolder url="file://$MODULE_DIR$/src/test/resources" type="java-test-resource"/>
      <sourceFolder url="file://$MODULE_DIR$/src/main/java" isTestSource="false"/>
      <sourceFolder url="file://$MODULE_DIR$/src/main/resources" type="java-resource"/>
      <excludeFolder url="file://$MODULE_DIR$/jeka/output"/>
      <excludeFolder url="file://$MODULE_DIR$/.idea/output"/>
    </content>
    <orderEntry type="sourceFolder" forTests="false"/>
    <orderEntry type="module-library" scope="COMPILE" exported="">
      <library>
        <CLASSES>
          <root url="jar://$MODULE_DIR$/libs/amadeus.maho-master-SNAPSHOT.jar!/"/>
        </CLASSES>
        <JAVADOC/>
        <SOURCES/>
      </library>
    </orderEntry>
    <orderEntry type="module-library" scope="TEST" exported="">
      <library>
        <CLASSES>
          <root url="jar://$JEKA_USER_HOME$/cache/wrapper/0.8.9.RELEASE/dev.jeka.jeka-core.jar!/"/>
        </CLASSES>
        <JAVADOC>
          <root url="jar://$JEKA_USER_HOME$/cache/wrapper/0.8.9.RELEASE/libs-javadoc/dev.jeka.jeka-core-javadoc.jar!/"/>
        </JAVADOC>
        <SOURCES>
          <root url="jar://$JEKA_USER_HOME$/cache/wrapper/0.8.9.RELEASE/libs-sources/dev.jeka.jeka-core-sources.jar!/"/>
        </SOURCES>
      </library>
    </orderEntry>
  </component>
</module>
```
log:
```
D:\Amadeus\Chocological>jekaw sync
"C:\Program Files\AdoptOpenJDK\jdk-13.0.0.33-hotspot\\bin\java"  -cp "D:\Amadeus\Chocological\jeka\wrapper\*" dev.jeka.core.wrapper.Booter "D:\Amadeus\Chocological\." sync
Picked up JAVA_TOOL_OPTIONS: -Dsun.jnu.encoding=utf-8  -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=1080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=1080
Resolving dependencies  ...
│ 0 module leading to 0 artifact.
└ Done in 2 milliseconds.
Project Location : D:\Amadeus\Chocological
Published Module & version : amadeus:chocological:internal-SNAPSHOT
Sources : [D:\Amadeus\Chocological\src\main\java:all]
Resources : [D:\Amadeus\Chocological\src\main\resources:all, D:\Amadeus\Chocological\src\main\java:all & out:[**/*.java, *.java, **/package.html, package.html, **/doc-files, doc-files]]
Tests : [D:\Amadeus\Chocological\src\test\java:all]
Tests resources : [D:\Amadeus\Chocological\src\test\resources:all, D:\Amadeus\Chocological\src\test\java:all & out:[**/*.java, *.java, **/package.html, package.html, **/doc-files, doc-files]]
Java Source Version : 13
Source Encoding : UTF-8
Source file count : 0
Download Repositories : [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2]
Publish repositories : [file:/D:/Jeka/User/maven-publish-dir]
Declared Dependencies : 1 elements.
Defined Artifacts : [[main-artifact].jar, -sources.jar, -original.jar]

Execute 'java#showDependencies' to display details on dependencies.
Generating iml file on D:\Amadeus\Chocological\chocological-javac ...
│ Resolving dependencies  ...
│ │ 0 module leading to 1 artifact.
│ └ Done in 0 milliseconds.
│ Resolving dependencies  ...
│ │ 0 module leading to 1 artifact.
│ └ Done in 0 milliseconds.
│ Iml file generated at D:\Amadeus\Chocological\chocological-javac\chocological-javac.iml
└ Done in 745 milliseconds.
Generating iml file on D:\Amadeus\Chocological ...
│ Resolving dependencies  ...
│ │ 0 module leading to 0 artifact.
│ └ Done in 4 milliseconds.
│ Resolving dependencies  ...
│ │ 0 module leading to 1 artifact.
│ └ Done in 1 milliseconds.
│ Iml file generated at D:\Amadeus\Chocological\Chocological.iml
└ Done in 442 milliseconds.
Iml file detected : chocological-javac\chocological-javac.iml
Iml file detected : Chocological.iml
File generated at : D:\Amadeus\Chocological\.idea\modules.xml
```

**Comment by djeang** [comment]
The logs tell that generating iml file from your build class failed so it has generated iml against the built-in `JkCommands` class which does not declare any dependencies.
```
Generating iml file on D:\Amadeus\Chocological\chocological-javac ... 
│ Generating Iml failed : Try to generate it using -CC=JkCommands option.
```
I will append stacktrace logs in order you can debug further.

**Comment by NekoCaffeine** [comment]
https://oss.sonatype.org/content/repositories/snapshots/dev/jeka/jeka-core/HEAD-SNAPSHOT/jeka-core-HEAD-SNAPSHOT.jar Is it this one?

**Comment by NekoCaffeine** [comment]
It doesn't look like this build, but I used other methods to get the logs.
I hooked up the target method.
This also raises another question, which I will explain later in another issue.
```
Execute 'java#showDependencies' to display details on dependencies.
Generating iml file on D:\Amadeus\Chocological\chocological-javac ... 
│ java.lang.IllegalArgumentException: No static method found on class dev.jeka.core.tool.Main for method exec and param types [class sun.nio.fs.WindowsPath, class java.lang.String]
│ 	at dev.jeka.core.api.utils.JkUtilsReflect.invokeMethod(JkUtilsReflect.java:490)
│ 	at dev.jeka.core.api.utils.JkUtilsReflect.invokeStaticMethod(JkUtilsReflect.java:454)
│ 	at dev.jeka.core.api.java.JkClassLoader.invokeStaticMethod(JkClassLoader.java:136)
│ 	at dev.jeka.core.tool.Main.exec(Main.java:88)
│ 	at dev.jeka.core.tool.builtins.intellij.JkPluginIntellij.allIml(JkPluginIntellij.java:93)
│ 	at dev.jeka.core.tool.builtins.intellij.JkPluginIntellij.all(JkPluginIntellij.java:108)
│ 	at Build.sync(Build.java:122)
│ 	at Build.main(Build.java:127)
│ Generating Iml failed : Try to generate it using -CC=JkCommands option.
│ Resolving dependencies  ... 
│ │ 0 module leading to 0 artifact.
│ └ Done in 1 milliseconds.
│ Resolving dependencies  ... 
│ │ 0 module leading to 1 artifact.
│ └ Done in 0 milliseconds.
│ Iml file generated at D:\Amadeus\Chocological\chocological-javac\chocological-javac.iml
└ Done in 2869 milliseconds.
```

**Comment by djeang** [comment]
Note that iml files are mostly supposed to be generated in cmd. An Intellij plugin is under active development for better integration.

**Comment by NekoCaffeine** [comment]
I think this([Main#exec](https://github.com/jerkar/jeka/blob/3472764706f31adc24969bf1e0bbc6bc518ee38f/dev.jeka.core/src/main/java/dev/jeka/core/tool/Main.java#L86)) should be like this(` argList.add(args); `).
Because the actual type of `String...` is `String[]`.

**Comment by NekoCaffeine** [comment]
> Note that iml files are mostly supposed to be generated in cmd. An Intellij plugin is under active development for better integration.

By the way, I am looking forward to jeka's idea plugin, which should be cool.
