### ISSUE TITLE
Error generating IDE files from different roots

### ISSUE THREAD

**Issue by Chocohead** [jerkar/jeka#150]
Stumbled across this while trying out something else. When a file dependency is in a different file system root the relativisation done for IDE classpath fails:
```
java.lang.IllegalArgumentException: 'other' has different root
        at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:392)
        at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:44)
        at dev.jeka.core.api.tooling.eclipse.JkEclipseClasspathGenerator.writeClasspathEl(JkEclipseClasspathGenerator.java:408)
        at dev.jeka.core.api.tooling.eclipse.JkEclipseClasspathGenerator.writeClasspathEl(JkEclipseClasspathGenerator.java:287)
        at dev.jeka.core.api.tooling.eclipse.JkEclipseClasspathGenerator.writeFileDepsEntries(JkEclipseClasspathGenerator.java:247)
        at dev.jeka.core.api.tooling.eclipse.JkEclipseClasspathGenerator.writeDependenciesEntries(JkEclipseClasspathGenerator.java:376)
        at dev.jeka.core.api.tooling.eclipse.JkEclipseClasspathGenerator._generate(JkEclipseClasspathGenerator.java:183)
        at dev.jeka.core.api.tooling.eclipse.JkEclipseClasspathGenerator.generate(JkEclipseClasspathGenerator.java:146)
        at dev.jeka.core.tool.builtins.eclipse.JkPluginEclipse.files(JkPluginEclipse.java:75)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at dev.jeka.core.api.utils.JkUtilsReflect.invoke(JkUtilsReflect.java:229)
        at dev.jeka.core.tool.Engine.invokeMethodOnRunOrPlugin(Engine.java:282)
        at dev.jeka.core.tool.Engine.invokeMethodOnRunClassOrPlugin(Engine.java:261)
        at dev.jeka.core.tool.Engine.runProject(Engine.java:254)
        at dev.jeka.core.tool.Engine.launch(Engine.java:235)
        at dev.jeka.core.tool.Engine.execute(Engine.java:107)
        at dev.jeka.core.tool.Main.exec(Main.java:94)
        at dev.jeka.core.tool.builtins.eclipse.JkPluginEclipse.lambda$all$0(JkPluginEclipse.java:103)
        at dev.jeka.core.api.system.JkLog.execute(JkLog.java:132)
        at dev.jeka.core.tool.builtins.eclipse.JkPluginEclipse.all(JkPluginEclipse.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at dev.jeka.core.api.utils.JkUtilsReflect.invoke(JkUtilsReflect.java:229)
        at dev.jeka.core.tool.Engine.invokeMethodOnRunOrPlugin(Engine.java:282)
        at dev.jeka.core.tool.Engine.invokeMethodOnRunClassOrPlugin(Engine.java:261)
        at dev.jeka.core.tool.Engine.runProject(Engine.java:254)
        at dev.jeka.core.tool.Engine.launch(Engine.java:235)
        at dev.jeka.core.tool.Engine.execute(Engine.java:107)
        at dev.jeka.core.tool.Main.main(Main.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at dev.jeka.core.wrapper.Booter.main(Booter.java:56)
```
In theory just checking if `Path#getRoot` is the same for the project directory and the file dependency before relativising the dependency's path should allow avoiding the crash. Might not be an especially common use case to have dependencies scattered about multiple disks, but it's helpful when testing things you don't really want to move about first ;)

**Comment by djeang** [comment]
Sorry, i don't have a simply way to test it. Please can you kindly push a pull request if you find a way to fix it ?
