### ISSUE TITLE
Running command on java 11+ produces NoClassDefFoundError with sun.misc.Unsafe

### ISSUE THREAD

**Issue by Voiteh** [jerkar/jeka#166]
Running using intellij plugin but also from command like like
```
jeka JekaTestBuild compile
```
Produces this error
```
"C:\Program Files\OpenJDK\jdk-14.0.1\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\lib\idea_rt.jar=56118:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin" -Dfile.encoding=UTF-8 -p C:\Users\voitech\git\JekaTest\.idea\output\test;C:\Users\voitech\git\JekaTest\.idea\output\production;C:\Users\voitech\.jeka\cache\wrapper\0.9.0.M10\dev.jeka.jeka-core.jar -m dev.jeka.jeka.core/dev.jeka.core.tool.Main -CC=JekaTestBuild compile
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/Unsafe
	at dev.jeka.jeka.core/dev.jeka.core.api.utils.JkUtilsSystem.disableUnsafeWarning(JkUtilsSystem.java:72)
	at dev.jeka.jeka.core/dev.jeka.core.tool.Main.main(Main.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at dev.jeka.jeka.core/dev.jeka.core.api.utils.JkUtilsReflect.invoke(JkUtilsReflect.java:234)
	at dev.jeka.jeka.core/dev.jeka.core.api.utils.JkUtilsReflect.invokeMethod(JkUtilsReflect.java:480)
	at dev.jeka.jeka.core/dev.jeka.core.api.utils.JkUtilsReflect.invokeStaticMethod(JkUtilsReflect.java:436)
	at dev.jeka.jeka.core/dev.jeka.core.api.java.JkClassLoader.invokeStaticMethod(JkClassLoader.java:149)
	at dev.jeka.jeka.core/dev.jeka.core.tool.Main.main(Main.java:33)
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 11 more
```

I have seen few issues on github regarding that in other projects. In Jeka there is some workaround which I don't understand, yet to make this error silent  `ClassNotFoundException` should be caught explitly, but I guess that It would be better to find other solution than `Unsafe`

**Comment by Voiteh** [comment]
As here 
https://stackoverflow.com/questions/46454995/how-to-hide-warning-illegal-reflective-access-in-java-9-without-jvm-argument

maybe 
`--add-opens` option ?
