### ISSUE TITLE
Cun't run project based compilation -> 'other' is different type of Path

### ISSUE THREAD

**Issue by Voiteh** [jerkar/jeka#167]
Hi trying to build project based jar .
My env settings:
```
Windows 10 Home
Working Directory : C:\Users\voitech\git\JekaTest
Java Home : C:\Program Files\OpenJDK\jdk-14.0.1
Java Version : 14.0.1, Oracle Corporation
Jeka Version : 0.9.0.M10
Jeka Home : C:\Users\voitech\jeka
Jeka Def Repositories : [https://repo.maven.apache.org/maven2, file:/C:/Users/voitech/jeka/maven-publish-dir]
Jeka Repository Cache : C:\Users\voitech\jeka\cache\repo

Intellij Idea community 2020.1.1
```

 This is my project structure 
![obraz](https://user-images.githubusercontent.com/38067799/94336675-26193000-ffe5-11ea-8abe-7c9d58c5262b.png)

My build file
```
public class JekaTestBuild extends JkCommandSet {


    private final JkJavaProject jekaTestProject = JkJavaProject.of()
            .getPublication()
            .setModuleId("com.something:jeka-test")
            .setVersion("1.2.3")
            .__
            .getJarProduction()
            .getDependencyManagement()
            .addDependencies(JkDependencySet.of()
                    .and("org.apache.commons:commons-lang3:3.11")
                    .and("junit:junit:4.13", JkScope.TEST)
            ).__.__;

    public void compile() {
        jekaTestProject.getPublication()
                .getArtifactProducer()
                .makeAllArtifacts();
    }

    public static void main(String[] args) {
        JkInit.instanceOf(JekaTestBuild.class, args).compile();
    }

}
```
Running main function
```
"C:\Program Files\OpenJDK\jdk-14.0.1\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\lib\idea_rt.jar=51653:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\voitech\git\JekaTest\.idea\output\test;C:\Users\voitech\git\JekaTest\.idea\output\production;C:\Users\voitech\.jeka\cache\wrapper\0.9.0.M10\dev.jeka.jeka-core.jar JekaTestBuild
Making artifact com.something.jeka-test.jar ... 
│ Compilation and resource processing of production code ... 
│ │ Copying resource files to .\jeka\output\classes ... 
│ │ └ Done in 0 milliseconds.
│ │ Resolving dependencies with specified scopes [compile, provided] ... 
│ │ │ 1 module resolved to 1 artifact file.
│ │ └ Done in 277 milliseconds.
│ │ Exception in thread "main" java.lang.IllegalArgumentException: 'other' is different type of Path
│ │ 	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:400)
│ │ 	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42)
│ │ 	at dev.jeka.core.api.java.JkJavaCompiler.compileWhatMessage(JkJavaCompiler.java:168)
│ │ 	at dev.jeka.core.api.java.JkJavaCompiler.compile(JkJavaCompiler.java:129)
│ │ 	at dev.jeka.core.api.java.project.JkJavaProjectCompilation.runCompile(JkJavaProjectCompilation.java:260)
│ │ 	at dev.jeka.core.api.java.project.JkJavaProjectCompilation.run(JkJavaProjectCompilation.java:128)
│ │ 	at dev.jeka.core.api.java.project.JkJavaProjectCompilation.runIfNecessary(JkJavaProjectCompilation.java:140)
│ │ 	at dev.jeka.core.api.java.project.JkJavaProjectJarProduction.createBinJar(JkJavaProjectJarProduction.java:98)
│ │ 	at dev.jeka.core.api.depmanagement.JkStandardFileArtifactProducer.makeArtifact(JkStandardFileArtifactProducer.java:51)
│ │ 	at dev.jeka.core.api.depmanagement.JkArtifactProducer.makeArtifacts(JkArtifactProducer.java:35)
│ │ 	at dev.jeka.core.api.depmanagement.JkArtifactProducer.makeAllArtifacts(JkArtifactProducer.java:50)
│ │ 	at JekaTestBuild.compile(JekaTestBuild.java:34)
│ │ 	at JekaTestBuild.main(JekaTestBuild.java:38)

Process finished with exit code 1
```
What i have done wrong ?

Debugging leads to info that Jeka is trying to relativize 
`C:\Users\voitech\git\JekaTest` with `src\main\java`, but the types of this paths are different first one is absolute and second is relative

**Comment by djeang** [comment]
I think it's fixed on last snapshot (but I cannot test on Windows 10). Can you confirm please ?

**Comment by Voiteh** [comment]
Unfortunetly still ocures but on other line `JkResourceProcessor.java:142`
```
"C:\Program Files\OpenJDK\jdk-15\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3\lib\idea_rt.jar=61011:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\woipo\git\jeka-test\.idea\output\test;C:\Users\woipo\git\jeka-test\.idea\output\production;C:\Users\woipo\.jeka\cache\wrapper\0.9.0.M11\dev.jeka.jeka-core.jar JekaTestBuild
Making artifact com.something.jeka-test.jar ... 
│ Compilation and resource processing of production code ... 
│ │ Copying resource files to .\jeka\output\classes ... 
│ │ │ Exception in thread "main" java.lang.IllegalArgumentException: 'other' is different type of Path
│ │ │ 	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:400)
│ │ │ 	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42)
│ │ │ 	at dev.jeka.core.api.file.JkResourceProcessor.generate(JkResourceProcessor.java:142)
│ │ │ 	at dev.jeka.core.api.java.project.JkJavaProjectCompilation.processResources(JkJavaProjectCompilation.java:256)
│ │ │ 	at dev.jeka.core.api.java.project.JkJavaProjectCompilation.run(JkJavaProjectCompilation.java:126)
│ │ │ 	at dev.jeka.core.api.java.project.JkJavaProjectCompilation.runIfNecessary(JkJavaProjectCompilation.java:140)
│ │ │ 	at dev.jeka.core.api.java.project.JkJavaProjectJarProduction.createBinJar(JkJavaProjectJarProduction.java:98)
│ │ │ 	at dev.jeka.core.api.depmanagement.JkStandardFileArtifactProducer.makeArtifact(JkStandardFileArtifactProducer.java:51)
│ │ │ 	at dev.jeka.core.api.depmanagement.JkArtifactProducer.makeArtifacts(JkArtifactProducer.java:35)
│ │ │ 	at dev.jeka.core.api.depmanagement.JkArtifactProducer.makeAllArtifacts(JkArtifactProducer.java:50)
│ │ │ 	at JekaTestBuild.compile(JekaTestBuild.java:32)
│ │ │ 	at JekaTestBuild.main(JekaTestBuild.java:36)

Process finished with exit code 1
```

**Comment by djeang** [comment]
Can you retry using the last snapshot version please ?
