### ISSUE TITLE
Sonar plugin use outdated Sonar runner jar

### ISSUE THREAD

**Issue by amottier** [jerkar/jeka#181]
During Sonar plugin execution I got the following stack trace:
```
      ERROR: Error during Sonar runner execution
      java.lang.IllegalStateException: Fail to download libraries from server
        at org.sonar.runner.impl.Jars.dowloadFiles(Jars.java:78)
        at org.sonar.runner.impl.Jars.download(Jars.java:57)
        at org.sonar.runner.impl.JarDownloader.download(JarDownloader.java:46)
        at org.sonar.runner.impl.JarDownloader.checkVersionAndDownload(JarDownloader.java:37)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:71)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
        at org.sonar.runner.api.Runner.execute(Runner.java:100)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:53)
      Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.sonar.runner.impl.Jars.dowloadFiles(Jars.java:72)
        ... 12 more
```

According to [a post on SonarQube forum](https://community.sonarsource.com/t/fail-to-download-libraries-from-server-caused-by-java-lang-arrayindexoutofboundsexception-1/25310/2) it seems that it is due to an incompatibilty between an old version of the runner and a more recent version of the server.

Jeka include `sonar-runner-2.4.jar` that was released on 24-Apr-2014. Latest version of `sonar-scanner-api` (that replace `sonar-runner`) is now `2.16.1.361` and was released 29-Apr-2021.

So I guess an upgrade might solve the issue but, despite major version being the same, it seems that API changed (e.g. `org.sonar.runner.Main` that is used by Jeka Sonar plugin no longer exists in version `2.16.1.361`). So fixing the issue would require taking a closer look at API changes. Maybe [integration test](https://github.com/SonarSource/sonar-scanner-api/blob/2.16.1.361/its/it-simple-scanner/src/main/java/com/sonar/scanner/api/it/Main.java) can help figuring out the new implementation.

**Comment by djeang** [comment]
I agree the runner should be replaced by a newer one. 
I think also that this plugin should be moved out of Jeka-Core to become an external plugin (It is here for historical reason).

**Comment by djeang** [comment]
Jeka built-in plugins Jacoco and Sonar are removed from the main distribution in favor of up-to-date external plugins :
  * [Sonarqube Plugin](https://github.com/jerkar/sonarqube-plugin)
  * [Jacoco Plugin](https://github.com/jerkar/jacoco-plugin)
